// POSTS
const GET_POSTS = 'GET_POSTS'
const CREATE_POST = 'CREATE_POST'

// CATEGORIES
const GET_CATEGORIES = 'GET_CATEGORIES'

module.exports = {
    GET_POSTS,
    GET_CATEGORIES,
    CREATE_POST
}