// POSTS
const GET_POSTS = 'GET_POSTS'
const CREATE_POST = 'CREATE_POST'
const EDIT_POST = 'EDIT_POST'
const DELETE_POST = 'DELETE_POST'
const GET_POST_BY_ID = 'GET_POST_BY_ID'

// CATEGORIES
const GET_CATEGORIES = 'GET_CATEGORIES'

// COMMENTS
const GET_COMMENTS_BY_POST_ID = 'GET_COMMENTS_BY_POST_ID'
const EDIT_COMMENT = 'EDIT_COMMENT'
const DELETE_COMMENT = 'DELETE_COMMENT'
const CREATE_COMMENT = 'CREATE_COMMENT'

module.exports = {
    GET_POSTS,
    GET_CATEGORIES,
    CREATE_POST,
    EDIT_POST,
    DELETE_POST,
    GET_COMMENTS_BY_POST_ID,
    EDIT_COMMENT,
    DELETE_COMMENT,
    CREATE_COMMENT,
    GET_POST_BY_ID
}